---
name: Build release package

env:
  RELEASE_PYTHON_VERSION: "3.14.7"

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  Package:
    name: Build package for ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python project with uv
        uses: ./.github/workflows/actions/python-uv
        with:
          python_version: ${{ env.RELEASE_PYTHON_VERSION }}

      - name: 🔥 Test
        run: uv run --locked poe test

      - name: 🚒 Create test summary
        uses: test-summary/action@v2
        if: success() || failure()
        with:
          paths: ./.pytest_results.xml

      - name: 📦 Build package
        run: uv build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
