---
name: Build container

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Container:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Build container image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
